### ISSUE TITLE
Make repository public and add open source license

### ISSUE THREAD

**Issue by lafrenierejm** [ajburma/Software-Engineering#1]
What is the advantage of keeping the project source code private? It seems that it would be more beneficial to the developers and the community if this project were open source.
If we do publicize this repository, I would prefer to do so under the [ISC license](http://opensource.org/licenses/ISC).

**Comment by lafrenierejm** [comment]
Much appreciated.

**Comment by jackywangxr** [comment]
How to edit the proposal online? Like add my name.

**Comment by lafrenierejm** [comment]
@jackywangxr 
Typically, all contributors will maintain their own forks (top right corner in GitHub) of the project. All changes (both in documentation and actual codebase) will then happen in those forks; when a contributor wants a change that they've made to be included in the primary repository, they can issue a pull request to ask a maintainer (person in charge of the repository) to accept the change from that contributor's fork and patch it into the primary repository.
This is all stuff we can go over when we meet on Sunday, if you're up for that.
